### ISSUE TITLE
encodeJson expression language errors

### ISSUE THREAD

**Issue by rstjohn** [Asymmetrik/ansible-role-nifi#29]
Adding the expression language function ```${value:encodeJson()}``` prevents an UpdateAttribute processor from starting.  During debugging, @issenec identified a difference between the docker installation and the RPM installation when it comes to the contents of the ```lib/``` directory.

**Comment by issenec** [comment]
Performing `mvn clean install` on the apache/nifi project produces the same `lib/bootstrap` contents. The difference between the current Nifi image and the Docker bootstrap are the following nars which may be currently located at the `lib/` level instead of the `lib/bootstrap` level:

- accessors-smart-1.2.jar
- asm-5.0.4.jar
- commons-codec-1.11.jar
- commons-text-1.4.jar
- jBCrypt-0.4.1.jar
- jna-4.4.0.jar
- jna-platform-4.4.0.jar

**Comment by tequalsme** [comment]
This is an issue with the Nifi RPM, not this ansible role. See https://issues.apache.org/jira/browse/NIFI-6003
